# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sunmy/py-mysql-rab

pipelines:
  branches:
    master:
      - step:
          image: sunmy/py-mysql-rab
          script:
            - echo "start server"
            - /etc/init.d/redis-server start
            - /etc/init.d/rabbitmq-server start
            - /etc/init.d/mysql start
            - mysqladmin -u root password absamw
            - pip install --upgrade pip
            - pip install -r bull/requirements/dev.txt
            - cd  test/weixinoauthSimulator
            - sh start.sh &
            - cd ../../bull/
            - sh rm_migration.sh
            - sh scripts/init_test_db.sh
            - sh scripts/test_non_mq.sh
            - sh scripts/test_mq.sh

